default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password: password

development:
  <<: *default
  database: library_development

test:
  <<: *default
  database: library_test

production:
  <<: *default
  database: library_production
